'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import {
  FileText, Plus, Sparkles, Send, Eye, Trash2,
  X, Loader2, Search, Building2,
} from 'lucide-react';
import { reports as reportsApi, brands as brandsApi } from '@/lib/api';
import { AgencyTopNav } from '@/components/internal/AgencyTopNav';
import { LoadingPage, EmptyState, Badge } from '@/components/ui';

const TYPES = [
  { value:'weekly',   label:'Weekly Report',   desc:'7-day snapshot'             },
  { value:'monthly',  label:'Monthly Report',  desc:'Full month review'          },
  { value:'campaign', label:'Campaign Report', desc:'Tied to a specific campaign' },
  { value:'custom',   label:'Custom Report',   desc:'Any date range'              },
];
const TYPE_COLOR: Record<string,string>   = { weekly:'purple', monthly:'blue', campaign:'green', custom:'amber' };
const STATUS_COLOR: Record<string,string> = { draft:'gray', published:'green', archived:'amber' };

export default function ReportsPage() {
  const [items, setItems]         = useState<any[]>([]);
  const [loading, setLoading]     = useState(true);
  const [brandFilter, setBF]      = useState('');
  const [typeFilter, setTF]       = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [brands, setBrands]       = useState<any[]>([]);
  const [brandSearch, setBS]      = useState('');
  const [form, setForm]           = useState({ brand_id:'', title:'', type:'monthly', period_start:'', period_end:'' });
  const [creating, setCreating]   = useState(false);
  const [createError, setCE]      = useState('');
  const [generating, setGenerating] = useState<string|null>(null);
  const [publishing, setPublishing] = useState<string|null>(null);
  const [deleting, setDeleting]   = useState<string|null>(null);

  const setF = (k: string, v: string) => setForm(p => ({ ...p, [k]: v }));

  useEffect(() => {
    const p: Record<string,string> = {};
    if (brandFilter) p.brand_id = brandFilter;
    if (typeFilter)  p.type     = typeFilter;
    setLoading(true);
    reportsApi.list(p).then((r:any)=>setItems(r.data??[])).catch(()=>setItems([])).finally(()=>setLoading(false));
     if (brands.length === 0)
      brandsApi.list({ limit:'100' }).then((r:any)=>setBrands(r.data??[])).catch(()=>{});
  }, [brandFilter, typeFilter]);

  const openCreate = () => {
    setShowCreate(true); setCE('');
    setForm({ brand_id:'', title:'', type:'monthly', period_start:'', period_end:'' });
    if (brands.length === 0)
      brandsApi.list({ limit:'100' }).then((r:any)=>setBrands(r.data??[])).catch(()=>{});
  };

  const applyDates = (type: string) => {
    const now=new Date(), pad=(n:number)=>String(n).padStart(2,'0'),
          fmt=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
    if (type==='weekly') {
      const s=new Date(now); s.setDate(now.getDate()-7);
      setForm(p=>({...p,type,period_start:fmt(s),period_end:fmt(now)}));
    } else if (type==='monthly') {
      const s=new Date(now.getFullYear(),now.getMonth(),1),
            e=new Date(now.getFullYear(),now.getMonth()+1,0);
      setForm(p=>({...p,type,period_start:fmt(s),period_end:fmt(e)}));
    } else {
      setForm(p=>({...p,type}));
    }
  };

  const createReport = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.brand_id) { setCE('Please select a brand'); return; }
    if (!form.title)    { setCE('Please enter a title');  return; }
    setCreating(true); setCE('');
    try {
      const res:any = await reportsApi.create({
        brand_id:form.brand_id, title:form.title, type:form.type,
        period_start:form.period_start||null, period_end:form.period_end||null, status:'draft',
      });
      setItems(p=>[res.data?.report??res.data,...p]);
      setShowCreate(false);
    } catch(err:any) { setCE(err.message||'Failed to create report'); }
    finally { setCreating(false); }
  };

  const generate = async (id:string) => {
    setGenerating(id);
    try {
      await reportsApi.generateNarrative(id);
      setItems(p=>p.map(r=>r.id===id?{...r,narrative:'✓ Narrative generated by ARIA™'}:r));
    } catch(err:any) { alert(err.message||'ARIA could not generate narrative right now'); }
    finally { setGenerating(null); }
  };

  const publish = async (id:string) => {
    if (!confirm('Publish this report to the client portal?')) return;
    setPublishing(id);
    try {
      await reportsApi.publish(id);
      setItems(p=>p.map(r=>r.id===id?{...r,status:'published',published_at:new Date().toISOString()}:r));
    } catch(err:any) { alert(err.message||'Failed to publish'); }
    finally { setPublishing(null); }
  };

  const del = async (id:string, title:string) => {
    if (!confirm(`Delete "${title}"? This cannot be undone.`)) return;
    setDeleting(id);
    try { await reportsApi.delete(id); setItems(p=>p.filter(r=>r.id!==id)); }
    catch(err:any) { alert(err.message||'Failed to delete'); }
    finally { setDeleting(null); }
  };

  const filteredBrands = brandSearch ? brands.filter(b=>b.name.toLowerCase().includes(brandSearch.toLowerCase())) : brands;
  const selBrand = brands.find(b=>b.id===form.brand_id);

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <AgencyTopNav title="Reports" subtitle="Brand performance reports" />

      <div className="flex items-start justify-between mb-6 flex-wrap gap-3">
        <div>
          <h1 className="text-xl font-bold text-white">Reports</h1>
          <p className="text-sm text-white/40 mt-0.5">{items.length} report{items.length!==1?'s':''}</p>
        </div>
        <button onClick={openCreate} className="sabi-btn-primary flex items-center gap-2 px-4 py-2.5 text-sm">
          <Plus className="w-4 h-4"/>New Report
        </button>
      </div>

      <div className="flex items-center gap-3 mb-6 flex-wrap">
        <select className="sabi-input w-44 text-sm" value={brandFilter} onChange={e=>setBF(e.target.value)}>
          <option value="">All brands</option>
          {brands.map(b=><option className="bg-[#12122a]" key={b.id} value={b.id}>{b.name}</option>)}
        </select>
        <div className="flex items-center gap-1 p-1 bg-white/3 rounded-xl border border-white/5">
          {['', ...TYPES.map(t=>t.value)].map(v=>(
            <button key={v} onClick={()=>setTF(v)}
              className={`px-3 py-1.5 text-xs rounded-lg transition-all capitalize ${typeFilter===v?'bg-purple-600 text-white':'text-white/40 hover:text-white'}`}>
              {v||'All'}
            </button>
          ))}
        </div>
      </div>

      {/* Create modal */}
      {showCreate && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-[#12122a] border border-purple-500/20 rounded-2xl p-6 w-full max-w-md max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-5">
              <div>
                <h2 className="text-base font-bold text-white">New Report</h2>
                <p className="text-xs text-white/30 mt-0.5">Create a draft — then use ARIA to write the narrative</p>
              </div>
              <button onClick={()=>setShowCreate(false)} className="text-white/30 hover:text-white transition-colors">
                <X className="w-5 h-5"/>
              </button>
            </div>

            {createError&&<div className="bg-red-500/10 border border-red-500/20 rounded-lg p-3 text-red-400 text-sm mb-4">{createError}</div>}

            <form onSubmit={createReport} className="space-y-4">
              {/* Brand */}
              <div>
                <label className="text-xs text-white/50 mb-1.5 block">Brand *</label>
                {selBrand ? (
                  <div className="flex items-center gap-3 p-3 rounded-xl border border-purple-500/30 bg-purple-500/8">
                    <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center text-sm font-bold text-purple-300 flex-shrink-0">{selBrand.name[0]}</div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-white">{selBrand.name}</p>
                      <p className="text-xs text-white/40">{selBrand.industry}</p>
                    </div>
                    <button type="button" onClick={()=>setF('brand_id','')} className="text-white/30 hover:text-white transition-colors flex-shrink-0"><X className="w-4 h-4"/></button>
                  </div>
                ) : (
                  <div>
                    <div className="relative mb-2">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-white/30"/>
                      <input className="sabi-input pl-9 text-sm" placeholder="Search brands…" value={brandSearch} onChange={e=>setBS(e.target.value)} autoFocus/>
                    </div>
                    <div className="border border-white/8 rounded-xl overflow-hidden max-h-40 overflow-y-auto">
                      {filteredBrands.length===0
                        ? <p className="text-white/25 text-xs text-center py-4">{brands.length===0?'Loading brands…':'No brands match'}</p>
                        : filteredBrands.map(b=>(
                          <button type="button" key={b.id} onClick={()=>{setF('brand_id',b.id);setBS('');}}
                            className="w-full flex items-center gap-3 px-3 py-2.5 hover:bg-white/5 transition-all text-left border-b border-white/5 last:border-0">
                            <div className="w-7 h-7 rounded-lg bg-purple-500/20 flex items-center justify-center text-xs font-bold text-purple-300 flex-shrink-0">{b.name[0]}</div>
                            <div className="min-w-0"><p className="text-sm text-white truncate">{b.name}</p><p className="text-xs text-white/30">{b.industry}</p></div>
                          </button>
                        ))
                      }
                    </div>
                  </div>
                )}
              </div>

              {/* Type */}
              <div>
                <label className="text-xs text-white/50 mb-1.5 block">Report Type *</label>
                <div className="grid grid-cols-2 gap-2">
                  {TYPES.map(t=>(
                    <button type="button" key={t.value} onClick={()=>applyDates(t.value)}
                      className={`p-3 rounded-xl border text-left transition-all ${form.type===t.value?'border-purple-500/50 bg-purple-500/15':'border-white/5 hover:border-white/10 hover:bg-white/3'}`}>
                      <p className={`text-xs font-semibold ${form.type===t.value?'text-purple-300':'text-white/60'}`}>{t.label}</p>
                      <p className="text-[10px] text-white/25 mt-0.5">{t.desc}</p>
                    </button>
                  ))}
                </div>
              </div>

              {/* Title */}
              <div>
                <label className="text-xs text-white/50 mb-1.5 block">Report Title *</label>
                <input className="sabi-input" required
                  placeholder={`e.g. ${selBrand?.name??'Brand'} ${new Date().toLocaleString('en-NG',{month:'long'})} Performance Report`}
                  value={form.title} onChange={e=>setF('title',e.target.value)}/>
              </div>

              {/* Dates */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs text-white/50 mb-1.5 block">Period Start</label>
                  <input type="date" className="sabi-input text-sm" value={form.period_start} onChange={e=>setF('period_start',e.target.value)}/>
                </div>
                <div>
                  <label className="text-xs text-white/50 mb-1.5 block">Period End</label>
                  <input type="date" className="sabi-input text-sm" value={form.period_end} onChange={e=>setF('period_end',e.target.value)}/>
                </div>
              </div>

              <div className="flex gap-3 pt-1">
                <button type="submit" disabled={creating}
                  className="sabi-btn-primary flex-1 flex items-center justify-center gap-2 py-2.5 text-sm disabled:opacity-50">
                  {creating?<><Loader2 className="w-4 h-4 animate-spin"/>Creating…</>:<><FileText className="w-4 h-4"/>Create Report</>}
                </button>
                <button type="button" onClick={()=>setShowCreate(false)} className="px-4 text-sm text-white/40 hover:text-white transition-colors">Cancel</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* List */}
      {loading ? <LoadingPage label="Loading reports…"/> : items.length===0 ? (
        <EmptyState icon={FileText} title="No reports yet"
          description="Create a report, then use ARIA to generate a NarrativeAI™ executive summary."
          action={{ label:'Create First Report', onClick:openCreate }}/>
      ) : (
        <div className="space-y-3">
          {items.map(r=>(
            <div key={r.id} className="sabi-card p-5 hover:border-white/10 transition-all">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center flex-shrink-0">
                  <FileText className="w-5 h-5 text-blue-400"/>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="min-w-0">
                      <Link href={`/reports/${r.id}`} className="font-semibold text-white hover:text-purple-300 transition-colors line-clamp-1">{r.title}</Link>
                      <div className="flex items-center gap-2 mt-1 flex-wrap">
                        {r.brands?.name&&<span className="flex items-center gap-1 text-xs text-white/35"><Building2 className="w-3 h-3"/>{r.brands.name}</span>}
                        {r.period_start&&<span className="text-xs text-white/25">{r.period_start} → {r.period_end}</span>}
                        {r.published_at&&<span className="text-xs text-white/20">Published {new Date(r.published_at).toLocaleDateString('en-NG',{day:'numeric',month:'short'})}</span>}
                      </div>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <Badge label={r.type}   color={TYPE_COLOR[r.type]??'gray'}/>
                      <Badge label={r.status} color={STATUS_COLOR[r.status]??'gray'}/>
                      {r.clarity_score&&<span className="text-xs font-bold text-purple-400">{r.clarity_score}</span>}
                    </div>
                  </div>
                  {r.narrative&&<p className="text-xs text-white/30 mt-2 line-clamp-2 leading-relaxed">{r.narrative}</p>}
                  <div className="flex items-center gap-4 mt-3 flex-wrap">
                    <Link href={`/reports/${r.id}`} className="flex items-center gap-1.5 text-xs text-white/40 hover:text-white transition-colors">
                      <Eye className="w-3.5 h-3.5"/>View
                    </Link>
                    {!r.narrative&&<button onClick={()=>generate(r.id)} disabled={generating===r.id}
                      className="flex items-center gap-1.5 text-xs text-purple-400 hover:text-purple-300 transition-colors disabled:opacity-40">
                      {generating===r.id?<><Loader2 className="w-3.5 h-3.5 animate-spin"/>Generating…</>:<><Sparkles className="w-3.5 h-3.5"/>Generate Narrative</>}
                    </button>}
                    {r.status==='draft'&&<button onClick={()=>publish(r.id)} disabled={publishing===r.id}
                      className="flex items-center gap-1.5 text-xs text-green-400 hover:text-green-300 transition-colors disabled:opacity-40">
                      {publishing===r.id?<><Loader2 className="w-3.5 h-3.5 animate-spin"/>Publishing…</>:<><Send className="w-3.5 h-3.5"/>Publish to Client</>}
                    </button>}
                    <button onClick={()=>del(r.id,r.title)} disabled={deleting===r.id}
                      className="flex items-center gap-1.5 text-xs text-red-400/50 hover:text-red-400 transition-colors disabled:opacity-40 ml-auto">
                      {deleting===r.id?<Loader2 className="w-3.5 h-3.5 animate-spin"/>:<Trash2 className="w-3.5 h-3.5"/>}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}