'use client';
import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, FileText, Plus, Sparkles, Send, Loader2, Eye } from 'lucide-react';
import { reports as reportsApi } from '@/lib/api';
import { LoadingPage, EmptyState, Badge, PageHeader } from '@/components/ui';

export default function BrandReportsPage() {
  const { id: brandId } = useParams<{ id: string }>();
  const router = useRouter();
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generatingId, setGeneratingId] = useState<string|null>(null);

  useEffect(() => {
    reportsApi.list({ brand_id: brandId, limit:'50' }).then((r:any)=>setItems(r.data??[])).finally(()=>setLoading(false));
  }, [brandId]);

  const generateNarrative = async (id: string) => {
    setGeneratingId(id);
    try {
      await reportsApi.generateNarrative(id);
      setItems(p=>p.map(r=>r.id===id?{...r,narrative:'✓ Narrative generated by ARIA'}:r));
    } catch {} finally { setGeneratingId(null); }
  };

  const publish = async (id: string) => {
    await reportsApi.publish(id);
    setItems(p=>p.map(r=>r.id===id?{...r,status:'published'}:r));
  };

  const TYPE_COLOR: Record<string,string> = { weekly:'purple', monthly:'blue', campaign:'green', custom:'amber' };

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <button onClick={() => router.back()} className="flex items-center gap-2 text-xs text-white/30 hover:text-white mb-5 transition-colors w-fit"><ArrowLeft className="w-3.5 h-3.5"/>Back</button>
      <PageHeader title="Reports" subtitle="Performance reports for this brand"
        action={<button className="sabi-btn-primary flex items-center gap-2 px-4 py-2 text-sm"><Plus className="w-4 h-4"/>New Report</button>}/>
      {loading?<LoadingPage/>:items.length===0?<EmptyState icon={FileText} title="No reports yet" description="Create a report and use ARIA to generate a NarrativeAI™ executive summary."/>:(
        <div className="space-y-3">
          {items.map(r=>(
            <div key={r.id} className="sabi-card p-5">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center flex-shrink-0"><FileText className="w-5 h-5 text-blue-400"/></div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div>
                      <Link href={`/reports/${r.id}`} className="font-semibold text-white hover:text-purple-300 transition-colors">{r.title}</Link>
                      <p className="text-xs text-white/40 mt-0.5">{r.period_start&&`${r.period_start} → ${r.period_end}`}</p>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <Badge label={r.type} color={TYPE_COLOR[r.type]??'gray'}/>
                      <Badge label={r.status} color={r.status==='published'?'green':'gray'}/>
                    </div>
                  </div>
                  {r.narrative&&<p className="text-xs text-white/30 mt-2 line-clamp-1">{r.narrative}</p>}
                  <div className="flex items-center gap-3 mt-3">
                    <Link href={`/reports/${r.id}`} className="flex items-center gap-1.5 text-xs text-white/40 hover:text-white transition-colors"><Eye className="w-3.5 h-3.5"/>View</Link>
                    {!r.narrative&&<button onClick={()=>generateNarrative(r.id)} disabled={generatingId===r.id} className="flex items-center gap-1.5 text-xs text-purple-400 hover:text-purple-300 transition-colors disabled:opacity-50">
                      {generatingId===r.id?<Loader2 className="w-3.5 h-3.5 animate-spin"/>:<Sparkles className="w-3.5 h-3.5"/>}Generate Narrative
                    </button>}
                    {r.status==='draft'&&<button onClick={()=>publish(r.id)} className="flex items-center gap-1.5 text-xs text-green-400 hover:text-green-300 transition-colors"><Send className="w-3.5 h-3.5"/>Publish to Client</button>}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
