'use client';
import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, FileText, Sparkles, BarChart2 } from 'lucide-react';
import { clientPortal } from '@/lib/api';
import { LoadingPage, Badge } from '@/components/ui';

export default function ClientReportDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    clientPortal.report(id).then((r: any) => setReport(r.data?.report)).finally(() => setLoading(false));
  }, [id]);

  if (loading) return <LoadingPage label="Loading report…" />;
  if (!report)  return <div className="p-6 text-white/40">Report not found or not yet published.</div>;

  const metrics = report.metrics || {};

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <Link href="/client/reports" className="flex items-center gap-2 text-xs text-white/30 hover:text-white mb-5 transition-colors w-fit">
        <ArrowLeft className="w-3.5 h-3.5" /> Back to Reports
      </Link>

      {/* Header */}
      <div className="sabi-card p-6 mb-6">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center flex-shrink-0">
            <FileText className="w-6 h-6 text-blue-400" />
          </div>
          <div className="flex-1">
            <h1 className="text-xl font-bold text-white">{report.title}</h1>
            <p className="text-sm text-white/40 mt-1">
              {report.period_start && `Reporting Period: ${report.period_start} → ${report.period_end}`}
              {report.published_at && ` · Published ${new Date(report.published_at).toLocaleDateString()}`}
            </p>
            <div className="flex items-center gap-2 mt-2">
              <Badge label={report.type} color="blue" />
              {report.clarity_score && (
                <span className="text-xs font-bold text-purple-400">ClarityScore™: {report.clarity_score}</span>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Metrics */}
      {Object.keys(metrics).length > 0 && (
        <div className="sabi-card p-6 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <BarChart2 className="w-4 h-4 text-purple-400" />
            <h2 className="text-sm font-semibold text-white">Key Metrics</h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {Object.entries(metrics).map(([k, v]) => (
              <div key={k} className="bg-white/3 rounded-xl p-4 border border-white/5 text-center">
                <p className="text-2xl font-bold text-white">{String(v)}</p>
                <p className="text-xs text-white/40 mt-1 capitalize">{k.replace(/_/g, ' ')}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Narrative */}
      {report.narrative && (
        <div className="sabi-card p-6">
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="w-4 h-4 text-purple-400" />
            <h2 className="text-sm font-semibold text-white">Intelligence Summary</h2>
            <span className="text-xs text-purple-400/50">Generated by ARIA™</span>
          </div>
          <div className="space-y-4">
            {report.narrative.split('\n\n').filter(Boolean).map((para: string, i: number) => (
              <p key={i} className="text-white/70 leading-relaxed text-sm">{para}</p>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
